### ISSUE TITLE
Tracking issue for upstream thread

### ISSUE THREAD

**Issue by bmann** [fission-suite/go-ipfs#1]
See https://github.com/ipfs/go-ipfs/issues/3643

There are multiple open pull requests there. Needs review, rebasing with head, and then merging in.

**Comment by corntoole** [comment]
here are the initial PRs

- https://github.com/ipfs/go-ipfs-files
- https://github.com/ipfs/go-ipfs-cmds
- https://github.com/ipfs/go-ipfs
