### ISSUE TITLE
Should we disable github actions for this fork?

### ISSUE THREAD

**Issue by cbrake** [fission-suite/go-ipfs#15]
we have github actions generating PRs:

![image](https://user-images.githubusercontent.com/402813/148966013-8da00533-7e33-4272-9765-08182dc9bc01.png)

@bmann what do you think of disabling the github actions for this fork?

**Comment by justincjohnson** [comment]
It seems that someone else already disabled dependabot, so I closed out the existing alerts.

I also disabled the GH action workflows that were failing on every push.

Thanks @cbrake.  Closing this now.
