### ISSUE TITLE
Create a v0.12 branch with go-ds-s3 plugin

### ISSUE THREAD

**Issue by walkah** [fission-suite/go-ipfs#27]
You should be able to follow the instructions from the go-ds-s3 repo README: https://github.com/ipfs/go-ds-s3

Also, see the previous iterations (for past versions of go-ipfs).

**Comment by justincjohnson** [comment]
Done in the `ds-s3-v0.12.1` branch.  Will experiment with it next.

**Comment by justincjohnson** [comment]
Per discussion with @walkah and @forgondolin today, I'll hold off on any testing until we have observability in place and a proper test plan.

**Comment by walkah** [comment]
I'm going to boldly close this issue (since the branch is, indeed, created). Have created some infrastructure tasks for the actual test plan, etc.

**Comment by forgondolin** [comment]
![image](https://user-images.githubusercontent.com/43958948/160478160-9c43e458-2451-4b69-97cb-76716b3e1829.png)
